services:
  - type: web
    env: static
    name: anubis-web
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: anubis-api
          type: web
          property: url