services:
  - type: web
    env: static
    name: anubis-web
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://anubis-api-0i1y.onrender.com
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html